name: Learnig githubaction topic Envorment variable
on:
 workflow_dispatch:
jobs:
 Topic:
  runs-on: ubuntu-latest

  env:
   username: Ayush18

  steps:
    - name: "Say hellw to $username"
      run: echo "Hii my name is $username ${{vargs.FIRST_NAME}}"
    
 
