name: Greet Pull Request

on:
  workflow_dispatch:  # Manual trigger for testing/debugging
  pull_request:
    types: [opened]   # Trigger when a PR is opened

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Post Greeting Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Create a greeting comment on the PR
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hello! Thanks for your pull request. Our team will review it shortly. 🙌"
            })
